"""Initial migration

Revision ID: 708a0e262c72
Revises: c79f2724435b
Create Date: 2025-09-16 15:48:30.953578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708a0e262c72'
down_revision = 'c79f2724435b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###