"""Initial migration

Revision ID: c79f2724435b
Revises: 
Create Date: 2025-09-16 12:45:15.480487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79f2724435b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('collection_name', sa.String(length=255), nullable=False, comment='Chroma集合名称'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment='嵌入模型'),
    sa.Column('chunk_size', sa.Integer(), nullable=True, comment='文本分块大小'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True, comment='分块重叠'),
    sa.Column('retrieval_config', sa.JSON(), nullable=True, comment='检索配置'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='状态: active, archived, deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('file_count', sa.Integer(), nullable=True, comment='文件数量'),
    sa.Column('document_count', sa.Integer(), nullable=True, comment='文档块数量'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_name')
    )
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False, comment='所属知识库ID'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='对话标题'),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='会话ID'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('retrieval_config', sa.JSON(), nullable=True, comment='检索配置'),
    sa.Column('chat_config', sa.JSON(), nullable=True, comment='聊天配置'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活跃'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='最后消息时间'),
    sa.Column('message_count', sa.Integer(), nullable=True, comment='消息数量'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_conversations_id'), 'chat_conversations', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False, comment='所属知识库ID'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='原文件名'),
    sa.Column('file_type', sa.String(length=100), nullable=False, comment='文件类型'),
    sa.Column('mime_type', sa.String(length=200), nullable=True, comment='MIME类型'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='文件MD5哈希'),
    sa.Column('storage_path', sa.String(length=1000), nullable=True, comment='MinIO存储路径'),
    sa.Column('bucket_name', sa.String(length=255), nullable=True, comment='MinIO桶名'),
    sa.Column('object_key', sa.String(length=1000), nullable=True, comment='MinIO对象键'),
    sa.Column('processing_status', sa.String(length=50), nullable=True, comment='处理状态: pending, processing, completed, failed'),
    sa.Column('processing_error', sa.Text(), nullable=True, comment='处理错误信息'),
    sa.Column('processing_progress', sa.Integer(), nullable=True, comment='处理进度(0-100)'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='提取的文本内容'),
    sa.Column('extracted_metadata', sa.JSON(), nullable=True, comment='提取的元数据'),
    sa.Column('vectorization_status', sa.String(length=50), nullable=True, comment='向量化状态: pending, processing, completed, failed'),
    sa.Column('vectorization_error', sa.Text(), nullable=True, comment='向量化错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='处理完成时间'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='生成的文档块数量'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='所属对话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user, assistant, system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('message_type', sa.String(length=50), nullable=True, comment='消息类型: text, image, file'),
    sa.Column('retrieved_chunks', sa.JSON(), nullable=True, comment='检索到的文档块'),
    sa.Column('retrieval_score', sa.Float(), nullable=True, comment='检索相关性评分'),
    sa.Column('source_files', sa.JSON(), nullable=True, comment='来源文件信息'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='使用的AI模型'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='提示词token数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='回复token数'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='总token数'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='回复质量评分'),
    sa.Column('user_feedback', sa.String(length=20), nullable=True, comment='用户反馈: like, dislike'),
    sa.Column('message_metadata', sa.JSON(), nullable=True, comment='消息元数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False, comment='所属知识库ID'),
    sa.Column('file_id', sa.Integer(), nullable=False, comment='所属文件ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='文档块内容'),
    sa.Column('content_length', sa.Integer(), nullable=True, comment='内容长度'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='内容哈希'),
    sa.Column('chunk_index', sa.Integer(), nullable=True, comment='在文件中的块索引'),
    sa.Column('start_pos', sa.Integer(), nullable=True, comment='在原文档中的起始位置'),
    sa.Column('end_pos', sa.Integer(), nullable=True, comment='在原文档中的结束位置'),
    sa.Column('chunk_size', sa.Integer(), nullable=True, comment='分块大小'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True, comment='重叠大小'),
    sa.Column('vector_id', sa.String(length=255), nullable=True, comment='在向量数据库中的ID'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment='使用的嵌入模型'),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True, comment='向量维度'),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True, comment='文档块元数据'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='内容质量评分'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('vectorized_at', sa.DateTime(timezone=True), nullable=True, comment='向量化时间'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_chat_conversations_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###